/**
 * Supabase database types — manually maintained to match supabase/migrations/.
 *
 * In a polished setup this file is auto-generated by:
 *   npx supabase gen types typescript --project-id <id> > src/types/database.types.ts
 *
 * Until the project is connected, we keep this file in sync with the SQL
 * migrations. Mismatch between this file and the actual schema will cause
 * runtime errors — keep both in sync when adding/removing columns.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ---------------------------------------------------------------------------
// Enums (mirror SQL CREATE TYPE statements)
// ---------------------------------------------------------------------------

export type UserRole = 'admin' | 'editor' | 'viewer';

export type ProjectStatus =
  | 'planning'
  | 'pre_sale'
  | 'under_construction'
  | 'completed'
  | 'sold_out'
  | 'archived';

export type ProjectType =
  | 'residential'
  | 'commercial'
  | 'mixed_use'
  | 'office'
  | 'retail'
  | 'industrial';

export type MediaType =
  | 'image'
  | 'rendering'
  | 'floor_plan'
  | 'site_plan'
  | 'document'
  | 'video';

export type UnitStatus = 'available' | 'reserved' | 'sold' | 'unavailable';

export type DataSource = 'yad2' | 'madlan' | 'tax_authority' | 'manual' | 'other';

export type ListingType = 'sale' | 'rent' | 'transaction';

export type ScrapeStatus = 'pending' | 'running' | 'completed' | 'failed';

export type ReportType =
  | 'market_analysis'
  | 'competitor_analysis'
  | 'pricing_strategy'
  | 'general';

export type ReportStatus = 'draft' | 'published' | 'archived';

export type CacheType =
  | 'city_data'
  | 'competitor_search'
  | 'market_stats'
  | 'ai_report_input';

// ---------------------------------------------------------------------------
// Database
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: UserRole;
          phone: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: UserRole;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
        Relationships: [];
      };

      projects: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          project_type: ProjectType;
          status: ProjectStatus;
          address: string | null;
          city: string;
          neighborhood: string | null;
          latitude: number | null;
          longitude: number | null;
          gush: string | null;
          helka: string | null;
          developer_name: string | null;
          developer_contact: string | null;
          price_min: number | null;
          price_max: number | null;
          price_per_sqm_avg: number | null;
          currency: string;
          construction_start_date: string | null;
          expected_completion_date: string | null;
          actual_completion_date: string | null;
          total_units: number | null;
          available_units: number | null;
          floors: number | null;
          cover_image_url: string | null;
          external_ids: Json;
          tags: string[];
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          city: string;
          description?: string | null;
          project_type?: ProjectType;
          status?: ProjectStatus;
          address?: string | null;
          neighborhood?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          gush?: string | null;
          helka?: string | null;
          developer_name?: string | null;
          developer_contact?: string | null;
          price_min?: number | null;
          price_max?: number | null;
          price_per_sqm_avg?: number | null;
          currency?: string;
          construction_start_date?: string | null;
          expected_completion_date?: string | null;
          actual_completion_date?: string | null;
          total_units?: number | null;
          available_units?: number | null;
          floors?: number | null;
          cover_image_url?: string | null;
          external_ids?: Json;
          tags?: string[];
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['projects']['Insert']>;
        Relationships: [];
      };

      project_media: {
        Row: {
          id: string;
          project_id: string;
          media_type: MediaType;
          storage_path: string;
          public_url: string | null;
          file_name: string;
          file_size_bytes: number | null;
          mime_type: string | null;
          width: number | null;
          height: number | null;
          title: string | null;
          description: string | null;
          display_order: number;
          is_cover: boolean;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          storage_path: string;
          file_name: string;
          media_type?: MediaType;
          public_url?: string | null;
          file_size_bytes?: number | null;
          mime_type?: string | null;
          width?: number | null;
          height?: number | null;
          title?: string | null;
          description?: string | null;
          display_order?: number;
          is_cover?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['project_media']['Insert']>;
        Relationships: [];
      };

      project_units: {
        Row: {
          id: string;
          project_id: string;
          unit_number: string;
          floor: number | null;
          rooms: number | null;
          area_sqm: number | null;
          balcony_area_sqm: number | null;
          garden_area_sqm: number | null;
          parking_spots: number;
          storage_units: number;
          price: number | null;
          price_per_sqm: number | null;
          status: UnitStatus;
          direction: string | null;
          floor_plan_url: string | null;
          notes: string | null;
          sold_at: string | null;
          sold_price: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          unit_number: string;
          floor?: number | null;
          rooms?: number | null;
          area_sqm?: number | null;
          balcony_area_sqm?: number | null;
          garden_area_sqm?: number | null;
          parking_spots?: number;
          storage_units?: number;
          price?: number | null;
          price_per_sqm?: number | null;
          status?: UnitStatus;
          direction?: string | null;
          floor_plan_url?: string | null;
          notes?: string | null;
          sold_at?: string | null;
          sold_price?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['project_units']['Insert']>;
        Relationships: [];
      };

      market_listings: {
        Row: {
          id: string;
          source: DataSource;
          source_id: string;
          listing_type: ListingType;
          city: string;
          neighborhood: string | null;
          street: string | null;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          gush: string | null;
          helka: string | null;
          property_type: string | null;
          rooms: number | null;
          area_sqm: number | null;
          floor: number | null;
          total_floors: number | null;
          year_built: number | null;
          has_elevator: boolean | null;
          has_parking: boolean | null;
          has_balcony: boolean | null;
          has_storage: boolean | null;
          has_shelter: boolean | null;
          is_renovated: boolean | null;
          price: number | null;
          price_per_sqm: number | null;
          currency: string;
          source_url: string | null;
          raw_data: Json | null;
          listed_at: string | null;
          transaction_date: string | null;
          scraped_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source: DataSource;
          source_id: string;
          listing_type: ListingType;
          city: string;
          neighborhood?: string | null;
          street?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          gush?: string | null;
          helka?: string | null;
          property_type?: string | null;
          rooms?: number | null;
          area_sqm?: number | null;
          floor?: number | null;
          total_floors?: number | null;
          year_built?: number | null;
          has_elevator?: boolean | null;
          has_parking?: boolean | null;
          has_balcony?: boolean | null;
          has_storage?: boolean | null;
          has_shelter?: boolean | null;
          is_renovated?: boolean | null;
          price?: number | null;
          price_per_sqm?: number | null;
          currency?: string;
          source_url?: string | null;
          raw_data?: Json | null;
          listed_at?: string | null;
          transaction_date?: string | null;
          scraped_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['market_listings']['Insert']>;
        Relationships: [];
      };

      scraping_jobs: {
        Row: {
          id: string;
          source: DataSource;
          target_params: Json;
          status: ScrapeStatus;
          items_found: number | null;
          items_new: number | null;
          items_updated: number | null;
          items_failed: number | null;
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          triggered_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source: DataSource;
          target_params?: Json;
          status?: ScrapeStatus;
          items_found?: number | null;
          items_new?: number | null;
          items_updated?: number | null;
          items_failed?: number | null;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          triggered_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['scraping_jobs']['Insert']>;
        Relationships: [];
      };

      project_reports: {
        Row: {
          id: string;
          project_id: string;
          report_type: ReportType;
          status: ReportStatus;
          title: string;
          content_html: string;
          ai_original_text: string | null;
          model_name: string | null;
          prompt_token_count: number | null;
          completion_token_count: number | null;
          input_snapshot: Json | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          content_html: string;
          report_type?: ReportType;
          status?: ReportStatus;
          ai_original_text?: string | null;
          model_name?: string | null;
          prompt_token_count?: number | null;
          completion_token_count?: number | null;
          input_snapshot?: Json | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['project_reports']['Insert']>;
        Relationships: [];
      };

      market_cache: {
        Row: {
          id: string;
          cache_type: CacheType;
          cache_key: string;
          data: Json;
          data_source: string | null;
          expires_at: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          cache_type: CacheType;
          cache_key: string;
          data: Json;
          expires_at: string;
          data_source?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['market_cache']['Insert']>;
        Relationships: [];
      };

      project_tabs: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['project_tabs']['Insert']>;
        Relationships: [];
      };

      project_tab_files: {
        Row: {
          id: string;
          tab_id: string;
          project_id: string;
          name: string;
          file_path: string;
          file_size: number;
          mime_type: string;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tab_id: string;
          project_id: string;
          name: string;
          file_path: string;
          file_size: number;
          mime_type: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['project_tab_files']['Insert']>;
        Relationships: [];
      };
    };

    Views: {
      v_price_trends_by_city: {
        Row: {
          city: string;
          month: string;
          avg_price: number | null;
          median_price: number | null;
          listing_count: number | null;
        };
        Relationships: [];
      };
      v_neighborhood_comparison: {
        Row: {
          city: string;
          neighborhood: string | null;
          avg_price_per_sqm: number | null;
          listing_count: number | null;
        };
        Relationships: [];
      };
      v_project_market_comparison: {
        Row: {
          project_id: string;
          project_name: string;
          city: string;
          neighborhood: string | null;
          project_price_per_sqm: number | null;
          market_avg_price_per_sqm: number | null;
          market_median_price_per_sqm: number | null;
        };
        Relationships: [];
      };
      v_scraping_health: {
        Row: {
          source: DataSource;
          last_run_at: string | null;
          last_status: ScrapeStatus | null;
          total_runs_7d: number | null;
          failed_runs_7d: number | null;
        };
        Relationships: [];
      };
    };

    Functions: Record<string, never>;

    Enums: {
      user_role: UserRole;
      project_status: ProjectStatus;
      project_type: ProjectType;
      media_type: MediaType;
      unit_status: UnitStatus;
      data_source: DataSource;
      listing_type: ListingType;
      scrape_status: ScrapeStatus;
      report_type: ReportType;
      report_status: ReportStatus;
      cache_type: CacheType;
    };
  };
}
